services:
  mariadb:
    image: mariadb:11
    container_name: erapport-mariadb
    environment:
      MARIADB_DATABASE: erapport
      MARIADB_USER: erapport
      MARIADB_PASSWORD: erapport
      MARIADB_ROOT_PASSWORD: erapport-root
    ports:
      - "3306:3306"

    volumes:
      - /mnt/dockervol/rapporteval/erapport-mariadb-data:/var/lib/mysql

    restart: unless-stopped

  server:
    build: ./server
    container_name: erapport-server
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_DATABASE: erapport
      MARIADB_USER: erapport
      MARIADB_PASSWORD: erapport
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: ""
    container_name: erapport-client
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5
    container_name: erapport-phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    restart: unless-stopped
